### ISSUE TITLE
Auto sort does not work

### ISSUE THREAD

**Issue by M3L6H** [M3L6H/Bloom#86]
Clicking the auto sort button currently throws a 503. That needs to be fixed.

**Comment by stickmanbob** [comment]
Issue was due to an error in MongoDB. The demo user's habits array had a habit id that pointed to a non existent habit (likely deleted). I cleaned up the database, which seems to have resolved the issue. Going forward please do not delete habits or modify the demo user directly on MongoDB or using postman
